spring:
  application:
    name: hello-elk
  elasticsearch:
    uris: http://demo.ynu.icu:9200
    username: elastic
    password: elastic
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useServerPrepStmts=true
    username: root
    password: x.z.w.91