server:
  port: 8020
spring:
  application:
    name: log-manager-server-statistic
  elasticsearch:
    uris: http://demo.ynu.icu:9200
    username: elastic
    password: elastic
    connection-timeout: 10s
    socket-timeout: 5s
  datasource:
    url: jdbc:mysql://localhost:3306/log_manager_server_statistic?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useServerPrepStmts=true
    username: root
    password: x.z.w.91
  cloud:
    nacos:
      server-addr: localhost:8848
log-record:
  enable: true
  group-name: dev
  pool:
    name: "log-record-thread-pool"
    core-size: 3
    max-size: 10
    keep-alive-time: 30
    time-unit: seconds
    rejectedExecutionHandler: java.util.concurrent.ThreadPoolExecutor.CallerRunsPolicy
  persistence:
    file:
      enable: true
      dir: D:\export\logs\logmanager
    logstash:
      enable: true
      host: demo.ynu.icu
      operate-log-port: 4560
      app-log-port: 4561
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level:
    com.example.xiao.logmanager.api.feign: debug