server:
  port: 8001
spring:
  application:
    name: log-manager-system-admin
  datasource:
    url: jdbc:mysql://localhost:3306/log_manager_server_user?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useServerPrepStmts=true
    username: root
    password: M.asd123.ysql
  cloud:
    nacos:
      server-addr: localhost:8848
log-record:
  enable: true
  group-name: dev
  persistence:
    file:
      enable: true
      dir: D:\export\logs\logmanager
    logstash:
      enable: true
      host: demo.ynu.icu
      operate-log-port: 4560
      app-log-port: 4561

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level:
    com.example.xiao.logmanager.server.user.dao: debug
