server:
  port: 8001
spring:
  application:
    name: log-manager-user-center
  datasource:
    url: jdbc:mysql://localhost:3306/log_manager_server_user?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useServerPrepStmts=true
    username: root
    password: M.asd123.ysql
  cloud:
    nacos:
      server-addr: localhost:8848
log-record:
  enable: true
  group-name: dev
  persistence:
    logstash:
      enable: true
      host: demo.ynu.icu
      operate-log-port: 4560
      app-log-port: 4561