server:
  port: 8030
spring:
  application:
    name: log-manager-server-messaging
  datasource:
    url: jdbc:mysql://localhost:3306/log_manager_server_user?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useServerPrepStmts=true
    username: root
    password: x.z.w.91
  cloud:
    nacos:
      server-addr: localhost:8848
  #邮箱配置
  mail:
    #平台地址，这里用的是企业微信邮箱，使用其他邮箱请更换
    host: smtp.exmail.qq.com
    port: 465
    username: xiaozhiwei@ynu.icu
    password: Xzw311818
    nickname: 日志中心
    properties:
      mail:
        smtp:
          ssl:
            enable: true

log-record:
  enable: true
  group-name: dev
  persistence:
    file:
      enable: true
      dir: D:\export\logs\logmanager
    logstash:
      enable: true
      host: demo.ynu.icu
      operate-log-port: 4560
      app-log-port: 4561