server:
  port: 8010
spring:
  application:
    name: log-manager-server-alert
  elasticsearch:
    uris: http://demo.ynu.icu:9200
    username: elastic
    password: elastic
    connection-timeout: 10s
  datasource:
    url: jdbc:mysql://localhost:3306/log_manager_server_alert?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useServerPrepStmts=true
    username: root
    password: x.z.w.91
  cloud:
    nacos:
      server-addr: localhost:8848
  rabbitmq:
    host: demo.ynu.icu
    port: 5672
    username: guest
    password: guest
log-record:
  enable: true
  group-name: dev
  pool:
    name: "log-record-thread-pool"
    core-size: 3
    max-size: 10
    keep-alive-time: 30
    time-unit: seconds
    rejectedExecutionHandler: java.util.concurrent.ThreadPoolExecutor.CallerRunsPolicy
  persistence:
    file:
      enable: true
      dir: D:\export\logs\logmanager
    logstash:
      enable: false