server:
  port: 8080

spring:
  application:
    name: log-manager-server-gateway

  cloud:
    gateway:
      #      跨域配置文件
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*" #允许的域名
            allowedHeaders: "*" #允许的请求头
            allowedMethods: "*" #允许的请求方法类型
            allowCredentials: true #是否允许cookie
      discovery:
        locator:
          enabled: true #开启后,新增一种访问方式:localhost:端口号/服务名/资源路径 原访问方式为localhost:端口号/资源路径
          lower-case-service-id: true #是否启动服务名小写,默认是大写
      routes:
        - id: log-manager-query-center     #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://log-manager-query-center       #匹配后提供服务的路由地址
          predicates:
            - Path=/api/log/search/**         # 断言，路径相匹配的进行路由
        - id: log-manager-user-center     #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://log-manager-user-center       #匹配后提供服务的路由地址
          predicates:
            - Path=/api/user/**         # 断言，路径相匹配的进行路由
      default-filters:
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
    nacos:
      discovery:
        server-addr: localhost:8848





